package com.parvaz.tunnel.core;
import android.app.Application;import android.content.*;import android.content.pm.*;import androidx.test.core.app.ApplicationProvider;
import com.parvaz.tunnel.model.*;import com.parvaz.tunnel.store.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.*;import java.io.*;import java.util.*;import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={29,34},application=Application.class) @LooperMode(LooperMode.Mode.PAUSED)
public class AuditRepairTest {
 Context app;ProfileStore store;
 @Before public void setup(){app=ApplicationProvider.getApplicationContext();ProfileStore.d=null;app.getSharedPreferences("parvaz_prefs",0).edit().clear().commit();app.getSharedPreferences("parvaz_store",0).edit().clear().commit();store=ProfileStore.f(app);AppLock.lock();}
 @Test public void widgetControlIsPrivate()throws Exception{ActivityInfo info=app.getPackageManager().getReceiverInfo(new ComponentName(app,ParvazWidget.class),0);assertFalse(info.exported);}
 @Test public void appLockDefaultAndExplicitAuthentication(){assertTrue(AppLock.allowed(app));app.getSharedPreferences("parvaz_prefs",0).edit().putBoolean("app_lock",true).commit();assertFalse(AppLock.allowed(app));AppLock.grant();assertTrue(AppLock.allowed(app));AppLock.lock();assertFalse(AppLock.allowed(app));}
 @Test public void everySensitiveActivityUsesGate()throws Exception{for(String n:new String[]{"MainActivity","SettingsActivity","CleanIpActivity","LogActivity","UsageActivity","RulesActivity","AutoProfileActivity","BackupRecoveryActivity","core.UpdateInstallActivity"})assertTrue(n,com.parvaz.tunnel.LockedActivity.class.isAssignableFrom(Class.forName("com.parvaz.tunnel."+n)));}
 @Test public void failedAuthenticationNeverGrants(){app.getSharedPreferences("parvaz_prefs",0).edit().putBoolean("app_lock",true).commit();AppLock.lock();assertFalse(AppLock.allowed(app));}
 @Test public void recentlyExpiredIsNotZeroDaysLeft(){long now=2000000000L;for(long n:new long[]{0,1,3600,86399,86400})assertEquals(-1,ExpiryState.daysRemaining(now-n,now));assertEquals(0,ExpiryState.daysRemaining(now+1,now));assertEquals(1,ExpiryState.daysRemaining(now+90000,now));}
 @Test public void millisecondsAndSecondsAgree(){long now=2000000000L;assertEquals(ExpiryState.daysRemaining(now+10,now),ExpiryState.daysRemaining((now+10)*1000,now));}
 @Test public void unlimitedDataStillWarnsOfFiniteExpiry(){QuotaNotifier.checkAndNotify(app,0,0,System.currentTimeMillis()/1000+3600);assertTrue(app.getSharedPreferences("parvaz_quota_notif",0).getBoolean("warned_expire",false));}
 @Test public void reportDropsConnectedAddressAndRemark(){String text=SafeLog.message("connected: private remark (vless secret-origin.invalid:443)");assertFalse(text.contains("secret-origin"));assertFalse(text.contains("private remark"));}
 @Test public void reportDropsCredentialsAndUrls(){String text=SafeLog.message("url=https://example.invalid/token?uuid=foo token=secretValue 11111111-1111-4111-8111-111111111111 192.0.2.1");for(String secret:new String[]{"example.invalid","secretValue","11111111","192.0.2.1"})assertFalse(text,text.contains(secret));}
 @Test public void stackNeverRetainsExceptionMessage(){String text=SafeLog.stack(new IOException("a secret token"));assertFalse(text.contains("a secret token"));assertTrue(text.contains("IOException"));}
 @Test public void nonCdnAndRealityAreNotEligible(){Profile p=profile();p.security="reality";p.sni="cover.invalid";assertFalse(CleanIpScanner.eligible(p));p.security="tls";assertFalse(CleanIpScanner.eligible(p));p.network="ws";assertTrue(CleanIpScanner.eligible(p));p.allowInsecure=true;assertFalse(CleanIpScanner.eligible(p));}
 @Test public void broadCleanIpApiCannotModifyAnything(){Profile p=profile();p.sni="cover.invalid";store.f346b.add(p);assertEquals(0,CleanIpScanner.applyCleanIpToCloudflareProfiles(app,"104.16.80.1"));assertEquals("origin.invalid",p.address);}
 @Test public void candidatePreservesTlsIdentity(){Profile p=profile();p.security="tls";p.network="ws";Profile c=CleanIpScanner.candidate(p,"104.16.80.1");assertEquals("origin.invalid",c.sni);assertEquals("origin.invalid",c.host);assertEquals("origin.invalid",p.address);assertEquals(-1,c.ping);}
 @Test public void manualMeasurementOwnsResultOverLiveSample()throws Exception{Profile p=profile();store.restoreRecords(Collections.singletonList(p),Collections.emptyList(),ProfileStore.MANUAL_GROUP);p=store.getActiveById(p.id);ProfileStore.Measurement m=store.beginMeasurement(p);store.i(p.id,20);assertTrue(store.ownsMeasurement(m));assertTrue(store.finishMeasurement(m,LatencyResult.HTTP_ERROR));assertEquals(LatencyResult.HTTP_ERROR,p.ping);}
 @Test public void syntheticLargeGeoIsRejected()throws Exception{File f=new File(app.getCacheDir(),"invalid-geo.dat");try(FileOutputStream out=new FileOutputStream(f)){byte[] b=new byte[80*1024];Arrays.fill(b,(byte)'X');out.write(b);}try{GeoData.tags(f,true);fail();}catch(IOException expected){}finally{f.delete();}}
 @Test public void structuralGeoTagsNotIncidentalAscii()throws Exception{File f=new File(app.getCacheDir(),"good-geo.dat");byte[] data={10,14,10,2,'I','R',18,8,10,4,1,2,3,4,16,24};try(FileOutputStream out=new FileOutputStream(f)){out.write(data);}assertEquals(Collections.singleton("ir"),GeoData.tags(f,true));f.delete();}
 @Test public void truncatedGeoFailsClosed()throws Exception{File f=new File(app.getCacheDir(),"truncated-geo.dat");try(FileOutputStream out=new FileOutputStream(f)){out.write(new byte[]{10,127,10});}try{GeoData.tags(f,true);fail();}catch(IOException expected){}f.delete();}
 @Test public void strictTargetDoesNotContainReadinessFallback(){String url=RealBypassTester.FILTERED_PROBE_URL;assertArrayEquals(new String[]{url},VerifiedProbe.endpoints(url,true));assertTrue(VerifiedProbe.endpoints(url,false).length>1);}
 @Test public void latencyBecomesHistoryOnNetworkChange(){LatencyStamp s=LatencyStamp.manual("YouTube");assertTrue(s.fresh());NetworkEpoch.changed();assertFalse(s.fresh());assertEquals("YouTube",s.target);}
 @Test public void snapshotsCannotMutateGlobalTuning(){android.content.SharedPreferences sp=app.getSharedPreferences("parvaz_prefs",0);sp.edit().putString("fragment_length","100-200").commit();java.util.Map<String,Object> overrides=new HashMap<>();overrides.put("fragment_length","1-3");SnapshotPreferences snapshot=new SnapshotPreferences(sp.getAll(),overrides);assertEquals("1-3",snapshot.getString("fragment_length",""));assertEquals("100-200",sp.getString("fragment_length",""));try{snapshot.edit();fail();}catch(UnsupportedOperationException expected){}}
 @Test public void endpointEditsAndUndoCannotTouchArchives()throws Exception{Profile active=profile(),archive=profile();active.security="tls";active.network="ws";archive.id="old";archive.subscriptionId="archived";store.restoreRecords(Arrays.asList(active,archive),Collections.emptyList(),ProfileStore.MANUAL_GROUP);ProfileStore.StartupLatency owner=store.captureStartupLatency(active);Profile candidate=CleanIpScanner.candidate(active,"104.16.80.1");assertTrue(store.replaceEndpoint(owner,candidate));assertEquals("origin.invalid",store.getById("old").address);assertFalse(store.replaceEndpoint(owner,active));assertTrue(store.replaceEndpoint(store.captureStartupLatency(candidate),active));assertEquals("origin.invalid",store.getById("a").address);}
 private Profile profile(){Profile p=new Profile();p.id="a";p.protocol="vless";p.address="origin.invalid";p.port=443;p.uuid="11111111-1111-4111-8111-111111111111";return p;}
}
