package com.parvaz.tunnel.core;
import org.junit.Test;
import java.util.concurrent.atomic.AtomicLong;
import static org.junit.Assert.*;
public class StartupDiagnosticsTest {
 @Test public void proofExpiresAcrossSuspendEvenWhenPhaseClockDoesNotAdvance(){AtomicLong phase=new AtomicLong(),bootMs=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,phase::get,bootMs::get);a.routeConfigured(true);a.coreStarted();a.probeFinished(true,10);bootMs.set(120000);assertFalse(a.proofFresh());assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());assertTrue(a.report().contains("proof_age_ms=120000"));}
 @Test public void oldCoreCannotRenewProofAfterResolverPolicyChanges(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt old=StartupDiagnostics.begin(0,0,now::get);old.routeConfigured(true);old.coreStarted();old.probeFinished(true,10);NetworkEpoch.resolverChanged();old.probeFinished(true,20,NetworkEpoch.current());assertFalse(old.proofFresh());StartupDiagnostics.Attempt fresh=StartupDiagnostics.begin(0,0,now::get);fresh.routeConfigured(true);fresh.coreStarted();fresh.probeFinished(true,30);assertTrue(fresh.proofFresh());}
 @Test public void trafficCannotKeepExpiredProofGreen(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.routeConfigured(true);a.coreStarted();a.probeFinished(true,10);assertTrue(a.proofFresh());assertFalse(a.proofDue());now.set(60_000_000_000L);assertTrue(a.proofDue());assertTrue(a.proofFresh());now.set(120_000_000_000L);a.received(100000);assertFalse(a.proofFresh());assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());a.probeFinished(true,15);assertTrue(a.proofFresh());}
 @Test public void networkRevisionRevokesProofAndRejectsOldPositiveSample(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.routeConfigured(true);a.coreStarted();long old=NetworkEpoch.current();a.probeFinished(true,10,old);NetworkEpoch.changed();assertFalse(a.proofFresh());a.probeFinished(true,20,old);assertFalse(a.proofFresh());a.probeFinished(true,25,NetworkEpoch.current());assertTrue(a.proofFresh());}
 @Test public void monotonicPhasesAreSeparateAndUnknownsAreNotZero(){
  AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,17,now::get);
  now.set(5_000_000);a.cleanupDone();now.set(12_000_000);a.configDone();now.set(20_000_000);a.coreStarted();
  String s=a.report();assertTrue(s.contains("vpn_setup_ms=17"));assertTrue(s.contains("previous_core_cleanup_ms=5"));assertTrue(s.contains("local_core_started_from_entry_ms=20"));assertTrue(s.contains("first_proxy_rx_observed_from_entry_ms=UNKNOWN"));assertTrue(s.contains("dns_ms=NOT_INSTRUMENTED"));assertTrue(s.contains("first_application_response_ms=NOT_INSTRUMENTED"));
 }
 @Test public void localCoreAloneDoesNotConfirmCommunication(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,-1,now::get);a.coreStarted();assertEquals(StartupDiagnostics.Confirmation.CHECKING,a.confirmation());now.set(13_000_000_000L);assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());}
 @Test public void proxyBytesCannotMasqueradeAsHttpOrApplicationResponse(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.coreStarted();a.received(100);assertEquals(StartupDiagnostics.Confirmation.CHECKING,a.confirmation());assertTrue(a.report().contains("first_application_response_ms=NOT_INSTRUMENTED"));}
 @Test public void unpinnedHttpResponseCannotTurnGreen(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.coreStarted();now.set(120_000_000);a.probeFinished(true,100);assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());assertTrue(a.report().contains("selected_remote_route=NOT_PROVEN"));}
 @Test public void supersededAttemptCannotChangeCurrentReport(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt old=StartupDiagnostics.begin(0,1,now::get);old.routeConfigured(true);old.coreStarted();StartupDiagnostics.Attempt current=StartupDiagnostics.begin(0,2,now::get);current.routeConfigured(true);current.coreStarted();old.probeFinished(true,10);old.received(100);assertEquals(StartupDiagnostics.Confirmation.CHECKING,StartupDiagnostics.confirmation());assertFalse(StartupDiagnostics.safeReport().contains("probe_duration_ms=10"));}
 @Test public void stoppedAttemptCannotBecomeConfirmedLater(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.routeConfigured(true);a.coreStarted();a.stop();a.probeFinished(true,10);assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());assertTrue(a.report().contains("session=STOPPED"));}
 @Test public void failedEndpointMeansUnconfirmedNotAForcedDisconnect(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.coreStarted();a.probeFinished(false,23);assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());assertTrue(a.report().contains("session=LATEST_CORE_ATTEMPT"));}
 @Test public void onlyFirstReceivedObservationIsStored(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,-1,now::get);a.coreStarted();a.received(0);now.set(200_000_000);a.received(1);now.set(400_000_000);a.received(9);assertTrue(a.report().contains("first_proxy_rx_observed_from_entry_ms=200"));}
 @Test public void repeatedFailureCanRevokeAndLaterRestoreGreenWithoutLosingFirstTiming(){AtomicLong now=new AtomicLong();StartupDiagnostics.Attempt a=StartupDiagnostics.begin(0,0,now::get);a.routeConfigured(true);a.coreStarted();now.set(100_000_000L);a.probeFinished(true,100);a.unconfirmed();assertEquals(StartupDiagnostics.Confirmation.UNCONFIRMED,a.confirmation());now.set(2_000_000_000L);a.probeFinished(true,50);assertEquals(StartupDiagnostics.Confirmation.RESPONSE_SEEN,a.confirmation());assertTrue(a.report().contains("first_proxy_http_response_from_entry_ms=100"));}
}
